name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  REMOTE_DIR: /opt/app
  SERVICE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # gradlew 위치 자동 탐지 (원하면 PROJECT_DIR를 직접 "."로 고정해도 됩니다)
      - name: Detect project directory
        shell: bash
        run: |
          set -e
          if [[ -f "./gradlew" ]]; then DIR="."; else
            FOUND=$(git ls-files | grep -E '(^|/)(gradlew)$' || true)
            [[ -z "$FOUND" ]] && { echo "gradlew not found"; exit 1; }
            DIR=$(dirname "$(echo "$FOUND" | head -n1)")
          fi
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
          echo "Detected PROJECT_DIR=$DIR"

      - name: Set up JDK 21 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build (Gradle bootJar)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test
          ls -lh build/libs/

      - name: Prepare remote dir (AL2023 over SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}       # 15.165.170.13
          username: ${{ secrets.EC2_USER }}   # ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 전체 내용 (BEGIN~END)
          script: |
            sudo mkdir -p ${{ env.REMOTE_DIR }}/upload
            sudo rm -f ${{ env.REMOTE_DIR }}/upload/*.jar

      - name: Upload JAR to EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "${{ env.PROJECT_DIR }}/build/libs/*.jar"
          target: "${{ env.REMOTE_DIR }}/upload"

      - name: Move & restart service (systemd on AL2023)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            JAR_PATH=$(ls -t ${{ env.REMOTE_DIR }}/upload/*.jar | head -n 1)
            echo "Using JAR: ${JAR_PATH}"
            sudo mv "${JAR_PATH}" ${{ env.REMOTE_DIR }}/app.jar
            sudo chown ec2-user:ec2-user ${{ env.REMOTE_DIR }}/app.jar
            sudo systemctl daemon-reload
            sudo systemctl restart ${{ env.SERVICE_NAME }}
            sleep 3
            sudo systemctl status ${{ env.SERVICE_NAME }} --no-pager | head -n 20
            curl -sI http://127.0.0.1:8080/ | head -n 1 || true
