name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]   # main 브랜치 푸시 시 배포

env:
  PROJECT_DIR: zanchi-backend-main/zanchi-backend-main   # ← 네 프로젝트 루트
  REMOTE_DIR: /opt/app
  SERVICE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest   # CI 러너 OS (배포 대상과 무관)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build (Gradle bootJar)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar -x test
          ls -lh build/libs/

      - name: Prepare remote dir (AL2023 over SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}         # 예: 15.165.170.13
          username: ${{ secrets.EC2_USER }}     # 예: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}   # pem 내용 전체
          script: |
            sudo mkdir -p ${{ env.REMOTE_DIR }}/upload
            sudo rm -f ${{ env.REMOTE_DIR }}/upload/*.jar

      - name: Upload JAR to EC2 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "${{ env.PROJECT_DIR }}/build/libs/*.jar"
          target: "${{ env.REMOTE_DIR }}/upload"

      - name: Move & restart service (systemd on AL2023)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            JAR_PATH=$(ls -t ${{ env.REMOTE_DIR }}/upload/*.jar | head -n 1)
            echo "Using JAR: ${JAR_PATH}"
            sudo mv "${JAR_PATH}" ${{ env.REMOTE_DIR }}/app.jar
            sudo chown ec2-user:ec2-user ${{ env.REMOTE_DIR }}/app.jar
            sudo systemctl daemon-reload
            sudo systemctl restart ${{ env.SERVICE_NAME }}
            sleep 3
            sudo systemctl status ${{ env.SERVICE_NAME }} --no-pager | head -n 20
            # 내부 헬스 확인(필요 시 엔드포인트 바꿔도 됨)
            curl -sI http://127.0.0.1:8080/ | head -n 1 || true
